In [1]:
# there are many ways to represent a model in julia

In [2]:
# tuple
# very efficient
# not flexible
# error-prone
model = (0.96, 0.1, 0.3, 4)

(0.96, 0.1, 0.3, 4)

In [3]:
model[1] # julia is 1-based indexing

0.96

In [4]:
model[1] = 3

LoadError: MethodError: no method matching setindex!(::Tuple{Float64, Float64, Float64, Int64}, ::Int64, ::Int64)
The function `setindex!` exists, but no method is defined for this combination of argument types.

In [6]:
sizeof(model)

32

In [7]:
sizeof(0.64)

8

In [8]:
# use a dictionary
# less error-prone

In [10]:
# instead of strings we use symbols
"a"

"a"

In [11]:
:a

:a

In [14]:
model2 = Dict(
:α => 0.3, # pair
:β => 0.96,
:γ => 4,
:δ => 0.1
)

Dict{Symbol, Real} with 4 entries:
  :α => 0.3
  :γ => 4
  :δ => 0.1
  :β => 0.96

In [15]:
model2[:α]

0.3

In [16]:
# dict are mutable
model2[:α] = 0.4

0.4

In [18]:
# doesn't have a predetermined representation in memory
isbits(model2)

false

In [19]:
# create a special julia-object: a struct

In [20]:
struct AModel
    α
    β
    γ
    δ
end

In [21]:
# create a model
mm = AModel(0.3, 0.96, 4, 0.1)

AModel(0.3, 0.96, 4, 0.1)

In [23]:
sizeof(mm) # we have an efficient object

32

In [24]:
# we can access fields with .
mm.α  # human friendly

0.3

In [26]:
mm[1] # it doesn't behave like a vector of parameters

LoadError: MethodError: no method matching getindex(::AModel, ::Int64)
The function `getindex` exists, but no method is defined for this combination of argument types.

In [27]:
struct BModel
    α::Float64
    β::Float64
    γ::Float64
    δ::Float64
end

# structures are good type optimization

In [ ]:

##

# namedtuples are great



In [66]:
# named arguments (with name=) on the right of ;
p = (;α=0.3, β=0.96, γ=4, δ=0.1)

(α = 0.3, β = 0.96, γ = 4, δ = 0.1)

In [ ]:
α = p.α
δ = p.δ

In [ ]:
# unpack tuples
α, β, γ, δ = tt

In [ ]:
# keyword unpacking

In [67]:
(;α, δ)=tt
# equivalent to 
# α = p.α
# δ = p.δ

(α = 0.3, β = 0.96, γ = 4, δ = 0.1)

In [30]:
isbits(tt)

true

In [34]:
# behave like tuples
tt[1]

0.3

In [35]:
# fields can be accessed with .
tt.α

0.3

In [ ]:
### functions



In [43]:
# strings:
"afkjh"
# triple quotes for multiline
"""
multi
lines
"""

"multi\nlines\n"

In [47]:
""" This is the docstring

a, b positional

"""
function fun(a,b)
    
    # return explicitly the result
    return a*b
    # the last line is the return value by default
    a+b    
end

fun

In [48]:
fun(3,3)



9

In [49]:
?fun

search: fun run



This is the docstring

a, b positional


In [50]:
# one liners



In [51]:
f(x,y) = (x+y)*exp(x)

f (generic function with 1 method)

In [52]:
f(3,3)

120.51322153912601

In [53]:
# anonymous functions

# parameters are given as tuples
(u,v) -> u^2 + v^2


#2 (generic function with 1 method)

In [54]:
((u,v) -> u^2 + v^2)(0.1,0.3)

0.1

In [56]:
# functions can have optional and keyword arguments

In [58]:
# c is an optional argument
function fadd(a,b,c=1)
    a + b*c
end

# this is equivalent to 
# function fadd(a,b)
#     c=1
#     a + b*c
# end
# function fadd(a,b,c)
#     a + b*c
# end

fadd (generic function with 2 methods)

In [64]:
fadd(1,2)

3

In [65]:
fadd(1,2,3)

7

In [59]:
#kwargs after ;
function fmul(a,b ; twice=false)
    if (twice == false)
        return a + b
    else
        return a + 2*b
    end
end

fmul (generic function with 1 method)

In [63]:
fmul(1,4; twice=true)

9

In [ ]:
# functions that modify their arguments
# have ! by convention

In [68]:
### vectors

In [69]:
# "look" like python lists

In [72]:
v = [3,4,2] # enclosed with square brackets

3-element Vector{Int64}:
 3
 4
 2

In [73]:
# behave like numpy arrays

In [74]:
2*v

3-element Vector{Int64}:
 6
 8
 4

In [75]:
# follow mathematical conventions

In [78]:
v .* v # the dot means element by element

3-element Vector{Int64}:
  9
 16
  4

In [79]:
f(x) = x^2

f (generic function with 2 methods)

In [81]:
f.(v)

3-element Vector{Int64}:
  9
 16
  4

In [84]:
v'*v # sacalar product with transpose '

29

In [ ]:
∈

# MAtrix

In [ ]:
[0.1 0.3 ; 0.2 0.4] # separate dimensions by ;

2×2 Matrix{Float64}:
 0.1  0.3
 0.2  0.4

In [13]:
M = zeros(3,3)
M[1,1] = 2.0 # one based index
M[1,2] = 4.0
M[1,3] = 5.0
M

3×3 Matrix{Float64}:
 2.0  4.0  5.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
M[:] # first index varies first

9-element Vector{Float64}:
 2.0
 0.0
 0.0
 4.0
 0.0
 0.0
 5.0
 0.0
 0.0

In [16]:
# generalizes to any number of dimensions
zeros(2,3,2)

2×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

In [19]:
M

3×3 Matrix{Float64}:
 2.0  4.0  5.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [18]:
M[:, 2] # slice notation: any row, second column

3-element Vector{Float64}:
 4.0
 0.0
 0.0

In [21]:
# M[:, size(M,2)]
M[:, end] # take last index of second dimension

3-element Vector{Float64}:
 5.0
 0.0
 0.0

In [22]:
# slice across both dimesions

M[1:2, 1:2]

2×2 Matrix{Float64}:
 2.0  4.0
 0.0  0.0